version: "3"
services:
  runtime:
    build:
      context: ..
      dockerfile: docker/runtime/dockerfile
    working_dir: "/usr/src/app"
    volumes:
      - ../angular:/usr/src/app
    entrypoint: bash -c "ng new app --skipGit --style scss --directory ./"
